### ISSUE TITLE
IoU result and how to test the model

### ISSUE THREAD

**Issue by sun0912704** [ISosnovik/nn4topopt#4] opened 2024-05-22 14:02 UTC
I am very sorry to bother you again. I would like to know how to test the network and how to get the data value or graph of IoU.

**Comment by ISosnovik** [comment] 2024-05-28 12:58
I dont' use tensorflow or keras at the moment
Try to reuse `results.ipynb` and extract what the model predicts for an input. If you extract the predictions as numpy arrays, then you can calculate IoU as follows


```python
def intersection_over_union(y_true, y_pred):
    # y_true: np.array with 0.0 and 1.0 only of shape [B, H, W, 1]
    # y_pred: np.arary with values from 0.0 to 1.0 of shape [B, H, W, 1]
    y_true = y_true.astype('int')
    y_true = y_true.reshape([len(y_true), -1])
    
    y_pred = (y_pred > 0.5).astype('int')
    y_pred = y_pred.reshape([len(y_pred), -1])
    
    n_0 = (y_true == 0).sum(-1)
    n_1 = (y_true == 1).sum(-1)
    
    w_00 = ((y_pred == 0) * (y_true == 0)).sum(-1)
    w_01 = ((y_pred == 0) * (y_true == 1)).sum(-1)
    w_10 = ((y_pred == 1) * (y_true == 0)).sum(-1)
    w_11 = ((y_pred == 1) * (y_true == 1)).sum(-1)
    
    iou_0 = w_00 / (n_0 + w_10 + 1e-16) 
    iou_1 = w_11 / (n_1 + w_01 + 1e-16)
    iou = (iou_0 + iou_1).mean(0) / 2.0
    return iou
 ```

**Comment by sun0912704** [comment] 2024-05-29 02:28
![image](https://github.com/ISosnovik/nn4topopt/assets/62976651/76317667-9b8f-47c7-9f3b-9fe13fe8b424)
How to get the picture's result?  I can't find the image's input and output to predict in the CNN.

**Comment by sun0912704** [comment] 2024-05-29 03:34
After training the model,I don't know how to use the model for one suitation topology optimization

**Comment by ISosnovik** [comment] 2024-05-30 13:24
The issue is a duplicate of https://github.com/ISosnovik/nn4topopt/issues/5

**Closed as completed** 2024-05-30 13:23 UTC
